base:
  base_dir: '../runs/'
  experiment: 'std'
dataset:
  pth: '/home/bian/project/data/Cephalometric/'
training:
  batch_size : 8
  num_workers : 8
  num_landmarks : 19
  lr : 0.001
  decay_step : 500
  decay_gamma : 0.8
  num_epochs : 3500
  save_seq : 100
  nearby : 6
  lambda : 2
  alpha : 0.99
  non_local: True
  conf: False
  patch_size: 192