base:
  base_dir: '../runs/'
  experiment: 'std'
  runs_dir: ../runs/std/S2
dataset:
  pth: '/home/bian/project/data/Cephalometric/'
training:
  runs_dir: ../runs/std/S2
  batch_size : 16
  num_workers : 16
  num_landmarks : 19
  lr : 0.0003
  decay_step : 50
  decay_gamma : 0.8
  num_epochs : 300
  save_seq : 100
  nearby : 6
  lambda : 2
  alpha : 0.99
  non_local: True
  conf: False
  patch_size: 196